modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/lazyMods/SnadBackThePast/issues"
license = "MIT"

[[mods]]
modId = "snad"
version = "${version}"
displayName = "Snad"
displayURL="https://www.curseforge.com/minecraft/mc-mods/snad-back-to-the-past"
authors = "lazy && TheRoBrit"
credits= "TheRoBrit the original mod creator."
description = '''
You're finally able to have your sugarcane grow faster. What could possibly be better than that?
'''
logoFile="logo.png"

[[dependencies.snad]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snad]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snad]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"